#!/bin/bash
set -e

echo "Standard $(bundle exec standardrb --format=progress)"
bundle exec standardrb --format progress $@
success=$?
if ((success != 0)); then
   echo -e "\nTry running \`script/fmt -a\` to automatically fix errors"
fi
exit $success
